#!/usr/bin/python3

from sys import argv
from math import sqrt


def factorize():
    with open(argv[1]) as file:
        for line in file:
            number = int(line)
            print(f"{number}=", end="")
            if number % 2 == 0:
                print(f"{number//2}*2")
                continue
            square_root = int(sqrt(number))
            if square_root % 2 == 0:
                square_root += 1
            for i in range(3, square_root + 1, 2):
                if number % i == 0:
                    print(f"{number//i}*{i}")
                    break
            if number % i != 0:
                print(f"{number}={number}*1")


factorize()
